ci:
  autoupdate_schedule: quarterly
repos:
  - repo: local
    hooks:
      - id: spotless-apply
        name: spotless-apply
        entry: mvn -q spotless:apply
        language: system
        pass_filenames: false
        files: \.java$

