name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ "11" ]

    steps:
      # Checkout Repo
      - uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Build with Ant
        run: |
         cp build.properties-template build.properties
         sudo mkdir -p /home/akrherz/ws/apache-tomcat-8.0.5/{bin,lib}
         ant compile
