name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ "11" ]

    steps:
      # Checkout Repo
      - uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Setup Tomcat
        run: |
          set -e
          wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.5/bin/apache-tomcat-8.0.5.tar.gz
          tar -xvf apache-tomcat-8.0.5.tar.gz
          sh apache-tomcat-8.0.5/bin/startup.sh

      - name: Build with Ant
        run: |
         set -e
         cp build.properties-template build.properties
         ant compile
